/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soomla_cocos2dx_store_EventHandlerBridge */

#ifndef _Included_com_soomla_cocos2dx_store_EventHandlerBridge
#define _Included_com_soomla_cocos2dx_store_EventHandlerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playPurchaseCancelled
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playPurchaseCancelled
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_soomla_cocos2dx_store_EventHandlerBridge
 * Method:    playPurchase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_soomla_cocos2dx_store_EventHandlerBridge_playPurchase
  (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
